apiVersion: v1
kind: PersistentVolume
metadata:
   name: local-pv
spec:
   storageClassName: local-storage
   capacity: 
      storage: 1Gi
   accessModes: 
      - ReadWriteOnce
   hostPath:
      path: "/mnt/local-k8s-storage"   

   