apiVersion: v1
kind: Service
metadata:
   name: pizza-service
   namespace: pizza
   labels:
      app: pizza-app
spec:
   selector:
      app: pizza-app
   type: NodePort
   ports:
      - protocol: TCP
        port: 80  
        targetPort: 80
        nodePort: 30080