apiVersion: v1
kind: Namespace
metadata:
    name: pizza
    labels:
       app: pizza-app        
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: pizza-app
   namespace: pizza
spec:
   selector:
      matchLabels:
         app: pizza-app
   replicas: 3
   template:
      metadata:
         labels:
            app: pizza-app
      spec:
         containers:
            - name: pizza
              image: linuxacademycontent/pizza-service:1.14.6
              command: ["nginx"]
              args: ["-g", "daemon off;"]
              ports:
                  - containerPort: 80
              livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
              readinessProbe:
                  httpGet:
                    path: /
                    port: 80