apiVersion: v1
kind: Pod
metadata:
   name: hw-secret-test
spec:
   containers:
      - name: hw-secret-test
        image: nginxdemos/hello:latest
        imagePullPolicy: Always
        ports:
           - name: default 
             containerPort: 80
        env:
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: my-test-secret
                   key: db_password
