apiVersion: v1
kind: Pod
metadata:
   name: hw-secret-test
spec:
   containers:
   - name: hw-secret-test
     image: nginxdemos/hello:latest
     imagePullPolicy: Always
     ports:
        - name: default
          containerPort: 80
     volumeMounts:
        - name: secrets-volume
          mountPath: /secrets
          readOnly: true
   volumes:
      - name: secrets-volume
        secret:
           secretName: my-test-secret