apiVersion: v1
kind: Service
metadata:
   name: hell-world-service
spec:
   selector:
      app: hello-world
   ports:
      - protocol: TCP
        port: 80  
        targetPort: 80
        nodePort: 30095
   type: NodePort